### PR TITLE
Fixed #24: Fixed edge case issue where constraint "> 0" does not hand…

### LINKED ISSUE #24: Ranges and pre-release bug
Consider the case of a range `> 0` and the versions `0.0.1-beta` and `0`.

This range will return false for both. But, isn't `0.0.1-beta` greater that `0`? If a range like `> 0-a` is used than a version like `0` doesn't work. It's one of those edge cases when #21/#23 was fixed.

@technosophos this came about when I was trying to update helm for the latest release to deal with the pre-release issue.

Considering two options:

1. Handling this special edge case in the code.
2. Adding a flag to the constraints struct for `UsingPrerelease` to force it into place without putting a prerelease on the constraint.

@technosophos @sdboyer thoughts?

### PR DESCRIPTION
**Pull request by mattfarina**
…le "0.0.1-alpha" properly.

### CODE REVIEW

**Comment by sdboyer** [comment]
so when i'd toyed with doing this before, i did something similar, except that i had a `uint8` field that i used to express a three-way distinction - zero, infinity, or "normal" version. here, you've just got the two-way distinction. this ends up being important for handling ranges correctly.

as long as this general problem is being dealt with here, perhaps it makes sense to handle all three?

**Comment by mattfarina** [comment]
@sdboyer I kept this entirely internal on purpose. I expected it will need to change. The reason I didn't handle a 3 way state out of the box (since we've talked about this before) is I couldn't come up with a use case for infinity. I expected it was my own lack of imagination at that time but it meant I couldn't write tests for infinity. Can you share a use case?

**Comment by sdboyer** [comment]
sure - infinity is the "value" that a range has if it's got no upper bound.

**Comment by sdboyer** [comment]
to be clear, i'm not sure i'm fully happy with having the three-way distinction, either. i'm gonna have a PR soon (today, i think) against 2.x that has an implementation, though, so we can have a look!

**Comment by mattfarina** [comment]
@sdboyer I moved the checking logic to the constraint checking rather than the version instances. It seemed cleaner. And, there's no need to store this state.

**Pull request merged**
