### PR TITLE
Fix pre-release precedence

### PR DESCRIPTION
**Pull request by uudashr**
Should follow the rule on https://semver.org/#spec-item-11

### CODE REVIEW

**Comment by uudashr** [comment]
@mattfarina any comment?

**Comment by uudashr** [comment]
@mattfarina please check

**Comment by uudashr** [comment]
@mattfarina does this project still actively maintained? would you check the PR?

**Comment by mattfarina** [comment]
@uudashr this project is maintained. Was just busy for a short period. Looking at this now.

**Comment by mattfarina** [comment]
@uudashr Thanks for finding the error in the tests and logic. A release will come out shortly.

**Comment by uudashr** [comment]
👍

**Pull request merged**
